export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_ERROR = "LOAD_PRODUCTS_ERROR";

export const LOAD_ORDERS_START = "LOAD_ORDERS_START";
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS";

export const ADD_CART = "ADD_CART";
export const ADD_CART_START = "ADD_CART_START";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_START = "DELETE_CART_START";

export const DECREMENT_CART_QUANTITY = "DECREMENT_CART_QUANTITY";
export const DECREMENT_CART_QUANTITY_START = "DECREMENT_CART_QUANTITY_START";

export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_CART_START = "CLEAR_CART_START";


export const GET_TOTALS="GET_TOTALS";
export const GET_TOTALS_START="GET_TOTALS_START";
export const OCCURED_ERROR = "OCCURED_ERROR";


export const CREATE_ORDER="CREATE_ORDER";
export const CREATE_ORDER_START="CREATE_ORDER_START";
export const CREATE_ORDER_ERROR="CREATE_ORDER_ERROR";


export const ADD_TO_WISHLIST=' ADD_TO_WISHLIST';
export const ADD_TO_WISHLIST_START=' ADD_TO_WISHLIST_START';



export const REMOVE_FROM_WISHLIST='REMOVE_FROM_WISHLIST';
export const REMOVE_FROM_WISHLIST_START='REMOVE_FROM_WISHLIST_START';
